name: release-tag

on:
  push

jobs:
  release-image:
    runs-on: ubuntu-latest
    env:
      DOCKER_ORG: teacup
      DOCKER_LATEST: nightly
      RUNNER_TOOL_CACHE: /toolcache
      FULL_TAG: ${{ vars.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Buildah and Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y buildah podman

      - name: Build image with buildah
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          tags: ${{ env.FULL_TAG }}
          containerfiles: |
            ./Dockerfile

      # Podman login action is broken for some reason
      # https://github.com/redhat-actions/podman-login/issues/41
      - name: Login to Gitea registry
        run: |
          podman login \
          --username "${{ secrets.DOCKER_USERNAME }}" \
          --password "${{ secrets.DOCKER_PASSWORD }}" \
          "${{ vars.REGISTRY }}"

      - name: Push to gitea internal registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ matrix.IMAGE_NAME }}
          tags: ${{ env.FULL_TAG }}
